### ISSUE TITLE
Make code look better and more understandable 

### ISSUE THREAD

**Issue by egkoppel** [EAZY-Code/sound-recorder#4]
Why is the variable called lol? https://github.com/EZ-Code-Developer/sound-recorder/blob/master/app/src/main/java/com/ezcode/recorder/SettingsActivity.java#L40

**Comment by zeevox** [comment]
Funny. This algorithm originates from stackoverflow.com, and isn't important as long as it functions (for now) Not an important issue, closed. [Source](http://stackoverflow.com/a/15538982).
